### ISSUE TITLE
Test code in Eclipse

### ISSUE THREAD

**Issue by guilhermekrz** [ramonpereira/Planning-Landmarks#1]
As I have added new libraries, I am not sure if the project will still compile in Eclipse. Need to test.

**Comment by guilhermekrz** [comment]
Failing here... I think it is because the project in Eclipse is set as Java 7, but in Intellij I set to Java 8. Is it okay to move to Java 8?

**Comment by ramonpereira** [comment]
That is ok. I am already using Java 8.

**Comment by guilhermekrz** [comment]
\o/, it was only my Eclipse that was configured to Java 8...
